### ISSUE TITLE
Getting the Promise state viewable by finally.

### ISSUE THREAD

**Issue by lygstate** [tc39/proposal-promise-finally#13]
Why not use 
.finally((state, error, value)) {
 so we know the Promise state after all
}

**Comment by ljharb** [comment]
@lygstate a) because promise callbacks only have one argument, and b) because you never need to know the state. If you want "resolve", you use `.then`, if you want "reject", you use `.catch`, and if you don't care what the fulfillment state is, you use `.finally`.

In other words, needing to know the state means you don't need `finally`.
